version: '2'

run:
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - err113
    - errorlint
    - goconst
    - gocritic
    - godot
    - godox
    - gosec
    - lll
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
    - wsl_v5

  settings:
    dogsled:
      max-blank-identifiers: 2

    dupl:
      threshold: 50

    errcheck:
      check-type-assertions: true
      check-blank: true

    errorlint:
      errorf: true

    goconst:
      min-len: 3
      min-occurrences: 3

    godot:
      capital: true
      scope: toplevel

    govet:
      enable-all: true

    lll:
      line-length: 120
      tab-width: 2

    nakedret:
      max-func-lines: 25

    nestif:
      min-complexity: 4

    nlreturn:
      block-size: 3

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    unparam:
      check-exported: true

    whitespace:
      multi-if: false
      multi-func: false

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - err

  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: '^exported: exported var Err[A-Za-z]+ should have comment or be unexported$'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: origin/main

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(go.jlucktay.dev)
        - prefix(go.jlucktay.dev/arrowverse)

    gofmt:
      simplify: true

    gofumpt:
      extra-rules: true

  exclusions:
    generated: lax
