# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.15"]

    name: Go ${{ matrix.go }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up module/build cache for Go
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          # In order:
          # - module download cache
          # - Linux build cache
          # cf. https://github.com/mvdan/github-actions-golang/blob/master/.github/workflows/test.yml
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          restore-keys: |
            ${{ runner.os }}-go-

      - run: make all

      - name: Send coverage to Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          flag-name: Go ${{ matrix.go }}
          path-to-profile: cover.out
